name: lscsq CI

on: [push]

jobs:
  lscsq-ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        sudo apt-get update
        sudo apt-get -y install gfortran
        sudo apt-get -y install libnetcdf-dev libnetcdff-dev
        sudo add-apt-repository ppa:remik-ziemlinski/nccmp
        sudo apt-get update
        sudo apt-get install nccmp
    - name: build
      run: |
        export FC=gfortran
        export F90=gfortran
        cd src
        make
        make install
    - name: CMOD
      run: cd ci_tests/cmod && ../../src/lsc_driver && diff lsc_out.cdf lsc_gcc.cdf
    - name: D3D
      run: cd ci_tests/D3D && ../../src/lsc_driver && diff lsc_out.cdf lsc_gcc.cdf
    - name: EAST
      run: cd ci_tests/EAST && ../../src/lsc_driver && diff lsc_out.cdf lsc_gcc.cdf
