name: lscsq CI

on: [push]

jobs:
  lscsq-ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        sudo apt-get update
        sudo apt-get -y install gfortran
        sudo apt-get -y install libnetcdf-dev libnetcdff-dev
        curl -L -o nccmp-1.8.3.1.tar.gz https://gitlab.com/remikz/nccmp/-/archive/1.8.3.1/nccmp-1.8.3.1.tar.gz
        tar -xzf nccmp-1.8.3.1.tar.gz
        cd nccmp-1.8.3.1
        chmod +x ./configure
        ./configure && make && sudo make install
    - name: pspline
      env:
        SSHK: ${{ secrets.PSPLINE_SECRET }}
      run: |
        mkdir -l $HOME/.ssh
        echo "$SSHK" > $HOME/.ssh/ssh.key
        chmod 600 $HOME/.ssh/ssh.key
        export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
        cd $HOME
        git clone git@github.com:PrincetonUniversity/pspline.git
        cd pspline
        make -j
        make install
    - name: build
      run: |
        export FC=gfortran
        export F90=gfortran
        export PSPLINE_HOME=$HOME/pspline/build
        cd src
        make
        make install
    - name: CMOD
      run: cd ci_tests/cmod && ../../src/lsc_driver && nccmp -dmgfsS lsc_out.cdf lsc_gcc.cdf
    - name: D3D
      run: cd ci_tests/D3D && ../../src/lsc_driver && nccmp -dmgfsS lsc_out.cdf lsc_gcc.cdf
    - name: EAST
      run: cd ci_tests/EAST && ../../src/lsc_driver && nccmp -dmgfsS lsc_out.cdf lsc_gcc.cdf
