name: lscsq CI

on: [push]

jobs:
  lscsq-ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        sudo apt-get -y install gfortran
        sudo apt-get -y install libnetcdf-dev libnetcdff-dev
    - name: build
      run: |
        export FC=gfortran
        export F90=gfortran
        export PREFIX=`pwd`
        cd src
        make
        make install
    - name: CMOD
      run: cd ci_tests/cmod && ../../bin/lsc_driver && diff lsc_out.cdf lsc_gcc.cdf
    - name: D3D
      run: cd ci_tests/D3D && ../../bin/lsc_driver && diff lsc_out.cdf lsc_gcc.cdf
    - name: EAST
      run: cd ci_tests/EAST && ../../bin/lsc_driver && diff lsc_out.cdf lsc_gcc.cdf
