name: Makefile CI

on: [push]

jobs:
  test-github-action:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: which gfortran
    - run: |
          gfortran --version
          pwd
          ls -al
          pushd ..
          wget https://w3.pppl.gov/~ethier/pspline_thread_safe.tar.gz
          tar -zxvf pspline_thread_safe.tar.gz
          cd pspline_thread_safe
          make -j 4
          make install
          popd
    - run: |
        sudo apt-get install -y libnetcdf-dev      
        sudo apt-get install -y libnetcdff-dev
        dpkg -L libnetcdff-dev
    - run: |
        cd src
        export NETCDF_FORTRAN_HOME=/usr/lib/x86_64-linux-gnu
        export PSPLINE_HOME=../../GCC-9.4
        F90=gfortran make
        ls -lrt


#    - run: find /usr -name 'libnetcdf*' -print

# Tests have not yet been implemented
#    - name: Run check
#      run: make check
#      
#    - name: Run distcheck
#      run: make distcheck

